{{- if and .Values.arangodb.auth.createSecret (not .Values.arangodb.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gremlin-arangodb-poc.secretName" . }}
type: Opaque
stringData:
  {{ .Values.arangodb.auth.usernameKey }}: {{ .Values.arangodb.auth.username | quote }}
  {{ .Values.arangodb.auth.passwordKey }}: {{ .Values.arangodb.auth.password | quote }}
{{- end }}
