apiVersion: v1
kind: Service
metadata:
  name: {{ include "gremlin-arangodb-poc.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "gremlin-arangodb-poc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: gremlin
      port: {{ .Values.service.port }}
      targetPort: gremlin
