# ruff: noqa: E501
import pytest

from opium_parser import Query, parse_opium

VALID_DOCUMENTED_EXPRESSIONS = [
    "get('users-data-product.user_roles')",
    'get("users-data-product.user_roles")',
    "get('users-data-product.user_roles', _key='admin')",
    "get('users-data-product.user_roles', 'permissions-data-product.abilities')",
    "get('users-data-product.user_roles').traverse()",
    "get('users-data-product.user_roles').traverse('users-data-product.user_role_subscriptions')",
    "get('users-data-product.user_roles').traverse(direction='inbound')",
    "get('users-data-product.user_roles').traverse(direction='outbound')",
    "get('users-data-product.user_roles').traverse(direction='any')",
    "get('users-data-product.user_roles').traverse(min_depth=1)",
    "get('users-data-product.user_roles').traverse(max_depth=4)",
    "get('users-data-product.user_roles').traverse(min_depth=2, max_depth=4)",
    "get('users-data-product.user_roles').traverse_any()",
    "get('users-data-product.user_roles').traverse_out()",
    "get('users-data-product.user_roles').traverse_in()",
    "get('users-data-product.user_roles').traverse_any('users-data-product.user_role_subscriptions')",
    "get('users-data-product.user_roles').traverse_out('users-data-product.user_role_subscriptions')",
    "get('users-data-product.user_roles').traverse_in('users-data-product.user_role_subscriptions')",
    "get('users-data-product.user_roles').traverse().into()",
    "get('users-data-product.user_roles').traverse().into('users-data-product.user_roles')",
    "get('users-data-product.user_roles').skip(0)",
    "get('users-data-product.user_roles').skip(100)",
    "get('users-data-product.user_roles').limit(1)",
    "get('users-data-product.user_roles').limit(100)",
    "get('users-data-product.user_roles').skip(100).limit(100)",
    "get('users-data-product.user_roles').count()",
    "get('users-data-product.user_roles').unique()",
    "get('users-data-product.user_roles').traverse().into().unique().count()",
    "get('users-data-product.user_roles').array(traverse().into())",
    "get('users-data-product.user_roles').array(traverse().into()).flatten()",
    "get('users-data-product.user_roles').array(traverse().into()).flatten(depth=1)",
    "get('users-data-product.user_roles').array(traverse().into()).flatten(depth=2)",
    "get('users-data-product.user_roles').as_var('role')",
    "get('users-data-product.user_roles').assign(traverse().into(), 'neighborhood')",
    "get('users-data-product.user_roles').assign(traverse().into(), 'neighborhood').select('_key')",
    "get('users-data-product.user_roles').select('_key', 'name')",
    "get('users-data-product.user_roles').select('_key', role=var('role'))",
    "get('users-data-product.user_roles').select('_key', role_id=var('role')['_id'])",
    "get('users-data-product.user_roles')['_key']",
    "get('users-data-product.user_roles')['_id']",
    "get('users-data-product.user_roles')['name']",
    "get('users-data-product.user_roles')[name]",
    "var('neighborhood')['_key']",
    "var('neighborhood')['_id']",
    "get('users-data-product.user_roles').match(_key='hello')",
    "get('users-data-product.user_roles').match(_key='hello', name='goodbye')",
    "get('users-data-product.user_roles').match(active=True)",
    "get('users-data-product.user_roles').match(active=False)",
    "get('users-data-product.user_roles').match(nullable_field=None)",
    "get('users-data-product.user_roles').match(nullable_field=null)",
    "get('users-data-product.user_roles').match(score=98.5)",
    "get('users-data-product.user_roles').match(age=64)",
    "get('users-data-product.user_roles').match(eq('_key', 'hello'))",
    "get('users-data-product.user_roles').match(ne('_key', 'hello'))",
    "get('users-data-product.user_roles').match(lt('age', 48))",
    "get('users-data-product.user_roles').match(gt('age', 48))",
    "get('users-data-product.user_roles').match(lte('age', 85))",
    "get('users-data-product.user_roles').match(gte('age', 85))",
    "get('users-data-product.user_roles').match(gt('age', 48), lte('age', 85))",
    "get('users-data-product.user_roles').match(age == 48)",
    "get('users-data-product.user_roles').match(age != 48)",
    "get('users-data-product.user_roles').match(age < 48)",
    "get('users-data-product.user_roles').match(age > 48)",
    "get('users-data-product.user_roles').match(age <= 85)",
    "get('users-data-product.user_roles').match(age >= 85)",
    "get('users-data-product.user_roles').match(value_in('_key', ['one']))",
    "get('users-data-product.user_roles').match(value_in('_key', ['one', 'two']))",
    "get('users-data-product.user_roles').match(nin('_key', ['one', 'two']))",
    "get('users-data-product.user_roles').match(is_null('missing_field'))",
    "get('users-data-product.user_roles').match(regex_matches('_key', '.*'))",
    "get('users-data-product.user_roles').match(regex_matches('_key', '^hello'))",
    "get('users-data-product.user_roles').match(regex_matches('_key', '^hello', caseInsensitive=True))",
    "get('users-data-product.user_roles').match_any(_key='hello', name='goodbye')",
    "get('users-data-product.user_roles').match_any(eq('_key', 'admin'), eq('_key', 'owner'))",
    "get('users-data-product.user_roles').match_all(eq('_key', 'admin'), gt('age', 10))",
    "match_any(eq('_key', 'admin'), eq('_key', 'owner'))",
    "match_all(eq('_key', 'admin'), gt('age', 10))",
    "eq('_key', 'admin')",
    "lt('age', 10)",
    "gt('age', 10)",
    "lte('age', 10)",
    "gte('age', 10)",
    "ne('_key', 'admin')",
    "value_in('_key', ['admin', 'owner'])",
    "nin('_key', ['viewer'])",
    "is_null('field')",
    "regex_matches('name', '^a')",
    "get('users-data-product.user_roles').match(eq(traverse().into()['_key'], 'admin'))",
    "get('users-data-product.user_roles').match(value_in(traverse().into()['_key'], ['admin']))",
    "get('users-data-product.user_roles').as_var('role').match(eq(var('role')['_key'], 'admin'))",
    "get('org-data-product.teams').match(eq(traverse_out('org-data-product.team_hierarchy', max_depth=2).into('org-data-product.teams')['_key'], 'executive'))",
    "get('users-data-product.user_roles').match(traverse_out('permissions-data-product.role_abilities').into('permissions-data-product.abilities').count() >= 3)",
    "get('platform-data-product.services').match(traverse_out('platform-data-product.service_dependencies').into('platform-data-product.services').unique().count() >= 3)",
    "get('users-data-product.user_roles').select('_key', is_admin=var('role')['_key'] == 'admin')",
    "get('users-data-product.user_roles').assign(array(traverse().into()), 'neighbors')",
    "get('users-data-product.user_roles').assign(array(traverse().into()['_key']), 'neighbors')",
    "get('users-data-product.user_roles').array(traverse().into()['_key']).flatten(depth=2)",
    "get('users-data-product.user_roles').match(match_any(eq('_key', 'admin'), eq('_key', 'owner')))",
    "get('users-data-product.user_roles').match(match_all(gt('age', 10), lt('age', 100)))",
    "get('users-data-product.user_roles').match(regex_matches('name', '^[AO]', caseInsensitive=False))",
    "get('users-data-product.user_roles').select('name', literal='constant')",
    "get('users-data-product.user_roles').select('name', missing=None)",
    "get('users-data-product.user_roles').select('name', enabled=True)",
    "get('users-data-product.user_roles').select('name', score=98.5)",
    "get('users-data-product.user_roles').match(value_in('category', ['internal', 'external']))",
    "get('users-data-product.user_roles').match(nin('category', ['external']))",
    "get('users-data-product.user_roles').traverse_out('permissions-data-product.role_abilities').select('_key', '_from', '_to')",
    "get('users-data-product.user_roles').traverse_out('permissions-data-product.role_abilities').select('_key', '_id', '_from', '_to')",
    "get('users-data-product.user_roles').traverse_out('permissions-data-product.role_abilities').into('permissions-data-product.abilities').select('_key', 'name')",
    "get('knowledge-data-product.documents', _key='doc-0').traverse_out('knowledge-data-product.document_links', max_depth=4).into('knowledge-data-product.documents').unique().count()",
    "get('platform-data-product.services').traverse_out('platform-data-product.service_dependencies', min_depth=2, max_depth=4)['_key']",
    "get('platform-data-product.services').traverse_out('platform-data-product.service_dependencies', min_depth=2, max_depth=4).into('platform-data-product.services')['_key']",
]


@pytest.mark.parametrize("source", VALID_DOCUMENTED_EXPRESSIONS)
def test_parse_documented_expression_matrix(source):
    assert isinstance(parse_opium(source), Query)
