image:
  repository: ron1510/gremlin-arangodb
  tag: 3.8.1-arangodb-4.0.0-arango311
  digest: sha256:bee0ad2ca8ed566218f0b18aad0e03432ff2a36622057bf5a1c6ec978b577eb6
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8182

gremlin:
  traversalSource: g
  logLevel: INFO

arangodb:
  host: arangodb.default.svc.cluster.local
  port: 8529
  database: my_db
  graph: my_graph
  orphanCollections: []
  edgeDefinitions:
    - depends_on:[services]->[services]
  graphType: COMPLEX
  enableDataDefinition: false
  auth:
    createSecret: true
    existingSecret: ""
    username: root
    password: change-me
    usernameKey: username
    passwordKey: password

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 100
  runAsGroup: 101
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

nameOverride: ""
fullnameOverride: ""
