nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: "ghcr.io/example/rest-cache-lab-backend"
  tag: "v0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10000
  runAsGroup: 10000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 256Mi
