{{- if and .Values.auth.createSecret (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arangodb-lab.secretName" . }}
type: Opaque
stringData:
  {{ .Values.auth.passwordKey }}: {{ .Values.auth.rootPassword | quote }}
{{- end }}
