apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rest-cache.fullname" . }}-vcl
  labels:
    {{- include "rest-cache.labels" . | nindent 4 }}
    app.kubernetes.io/component: varnish
data:
  default.vcl: |
{{- if .Values.varnish.vclConfig }}
{{ tpl .Values.varnish.vclConfig . | nindent 4 }}
{{- else }}
{{ include "rest-cache.defaultVcl" . | nindent 4 }}
{{- end }}
